
name: Build (only) ASP.Net Core app to Azure Web App - auction-pragmatic

permissions:
      id-token: write
      contents: read
      
on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        working-directory: ./Auction/Auction
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./Auction/Auction
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Install EF Core CLI
        run: dotnet tool install dotnet-ef --global
        shell: bash

      - name: Update database
        run: |
          cd ./Auction/Auction
          dotnet ef database update || exit 1
        shell: bash
        env:
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
